### ISSUE TITLE
SetSize / GetSize not working

### ISSUE THREAD

**Issue by panzors** [jieter/leaflet-headless#11]
Hi, I've been using this library and the GetSize/SetSize function doesn't seem to work. I've written my own hack for it to make it working.

Thanks for providing this library.

Either I'm using it incorrectly or it's always defaulting to 1024/1024

**Comment by jieter** [comment]
Can you show some code and provide detailed version numbers?

**Comment by jieter** [comment]
@panzors can you explain what doesn't work for you?

**Comment by panzors** [comment]
Huummm... It may have been introduced when I changed your source to use streams instead of writing directly to a file.
When I check the "getsize" function, it was always going to the default 1024.

Unable to reproduce in example. Probably just my modifications being weird.
