### ISSUE TITLE
Cannot read property '_leaflet_id' of null

### ISSUE THREAD

**Issue by SHDavies** [jieter/leaflet-headless#12]
I'm getting the above error in nearly all code I run, including the examples for this project. Maybe a result of updating leaflet to 1.0.0-rc.1

**Comment by jieter** [comment]
@SHDavies can you provide a stack trace?

**Comment by jieter** [comment]
I just did `rm -rf node_modules`, `npm install` and `npm test` which reports passes for the basic functions, it only fails for the image comparison...
