### ISSUE TITLE
WMS TileLayer Event / Multiple Tile Layer

### ISSUE THREAD

**Issue by bloigge** [jieter/leaflet-headless#14]
I would like to add a WMS Tile layer (data comes from a postgresql and the wms is created by geoserver) on top of my basemap.

The map.saveImage function should start when all Tiles from the overlay-layer are loaded. Therefor I put the function in the callback of the "on-load" event of the wms layer. Unfortunatly the callback never gets called. what am I missing?

```
	var datalayer = L.tileLayer.wms(url, { 
        format: 'image/png',
		minZoom: 13,
		maxZoom: 21,	
		maxNativeZoom: 19,
		zIndex: 10,
		transparent: true,
		layers: "Data:Layer"
	}).addTo(map);

datalayer.on("load", function() { map.saveImage(filename, callback) });
```

**Comment by jieter** [comment]
Did you try to get an image without waiting on the event? I'm not exactly sure if leaflet-headless wil try to load images without a call to to `map.saveImage()`...

**Comment by bloigge** [comment]
yes - but then only the basemap is rendered and I don't get any tiles form the overlay

**Comment by jieter** [comment]
And with only the overlay?

**Comment by bloigge** [comment]
oh well - that returns only a black image...

**Comment by jieter** [comment]
I'm not sure what the exact problem is here, but I can [get an image from a `L.TileLayer.WMS()` layer](https://github.com/jieter/leaflet-headless/blob/master/examples/tilelayer-wms/index.js#L13-L25): 
![example-leaflet-tilelayer-wms](https://cloud.githubusercontent.com/assets/1470389/15353255/682b9d14-1ce8-11e6-9df8-09b691d69030.png)

Also tried with `transparent: true`, same image.

**Comment by jieter** [comment]
This indeed makes the image black:

```JavaScript
L.tileLayer('http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png').addTo(map);

L.tileLayer.wms('http://demo.opengeo.org/geoserver/ows?', {
    layers: 'ne:ne',
    transparent: true
}).addTo(map);
```

**Comment by jieter** [comment]
seems to be a leaflet-image issue: if I add the wms layer from my previous comment to http://mapbox.github.io/leaflet-image/, the snapshot only has the wms + heatmap layer.

**Comment by bloigge** [comment]
ok - thank you for the investigations. Using your wms givs me tiles as well - also with the problem that I can't set the opacity when using two tileLayer.

But I think that using my geoserver is a different problem, because not a single tile shows up. 
Using the same setup on the client - just for viewing the wms from the geoserver - works fine (but the tiles need some time to show up). The geoserver we are using is on a very small machine, so I guess this is the problem for the delay --> therefor I thought using the  "on-load" event will do the trick.

**Comment by bloigge** [comment]
After some more investigations  I think that the L.tileLayer events aren't working proberly. even if I try to listen on an event from a wms layer that works - the callback never gets called.

**Comment by bloigge** [comment]
Ok I think the main problem is that format: 'image/png' is not working.
