### ISSUE TITLE
No markers visible

### ISSUE THREAD

**Issue by Lewons** [jieter/leaflet-headless#16]
L.marker([lat, lon]).addTo(map);

I am having problems with the above line. I want to add a marker to the location [lat, lon] but the code after this line is not being executed, the marker is not showing and there is absolutely no error message.

The code in question is as follows:

this.state.L.marker([lat, lon]).addTo(this.state.mapL);

where L and mapL are stored within the state, in order to treat them as sort of global variables.

Is there a solution for this problem?

Thank you.

**Comment by jieter** [comment]
Hmm, I doesn't see what could cause the program to stop without error message in this line. If you can provide a minimal, working example showing it's a leaflet-headless problem, please reopen and I'll look into it again.

In the mean time: try to read on how to debug your nodejs code: , for example: http://stackoverflow.com/questions/1911015/how-do-i-debug-node-js-applications

**Comment by Lewons** [comment]
I was able to solve this problem by setting my own marker. Somehow the standard marker icon was not found and no error message was shown.

**Comment by jieter** [comment]
interesting. What platform and node version are you on?

**Comment by mbejda** [comment]
Same on El Capitan.. This is the error I'm getting 
<img width="1024" alt="screen shot 2016-10-04 at 12 37 05 pm" src="https://cloud.githubusercontent.com/assets/5429780/19083236/57e7f2b8-8a2f-11e6-8d04-a77fdd3ff894.png">

**Comment by mbejda** [comment]
Its missing a `/`

**Comment by sainsb** [comment]
Receiving this error as well on Windows x64, node 6.9.1.
Instead of splitting on '/' I used path.sep, this works, but then one receives the message:
`Image not implemented for url: c:/projects/leaflet-headless/node_modules/leaflet/dist/images/marker-icon.png?cache=1477790544120`

**Comment by jieter** [comment]
@sainsb Thanks for reporting, just pushed the `path.sep` change. Apparently, node on windows does not have a `file://` protocol prefix, so we need a different way to remove the `cache=x` argument

**Comment by jieter** [comment]
fixed by b766f3a7e2cdfb8c4c5f17239ef78061dd7f7131
