### ISSUE TITLE
needs upgrade, not work with new nodejs versions

### ISSUE THREAD

**Issue by keremciu** [jieter/leaflet-headless#17]
firstly contextify is removed from jsdom

jsdom has a lot of changes needs update immediately

canvas has problems on windows

**Comment by jieter** [comment]
Currently, I have not much time to dive into this, but I'll me able to test and merge pull requests and do a release.

**Comment by keremciu** [comment]
Hello @jieter

nice to see your answer, I will give it a try, I hope I can send a good pull request

**Comment by jieter** [comment]
@keremciu any update? would be nice to have a working version with modern deps again.

**Comment by keremciu** [comment]
@jieter heya, yep, I've updated the dependencies, it is working nicely, I'll send you a pull request about it

**Comment by jieter** [comment]
PR on it's way?

**Comment by keremciu** [comment]
@jieter so sorry, I didn't see your comment before, I've sent the PR about my local working version of this repo, https://github.com/jieter/leaflet-headless/pull/18

**Comment by jieter** [comment]
fixed by b766f3a7e2cdfb8c4c5f17239ef78061dd7f7131

**Comment by keremciu** [comment]
@jieter ups, so thanks! but you should update the version on package.json, I can't install this one with npm

**Comment by jieter** [comment]
@keremciu yes, it was not released yet (only updating the version field in package.json doesn't do that), but I just released a new version containing the fixes.

**Comment by keremciu** [comment]
@jieter it is not working because of versions... https://github.com/keremciu/leaflet-headless/blob/6eb35e391d9ab2593a42cb6982c3d67bae464261/package.json I'm using node 6.9.2 and this version needs new versions of them, can we update them?

**Comment by jieter** [comment]
Hmm, apparently, I did not update jsdom :( Let me look into it.

**Comment by keremciu** [comment]
also sorry about my PR, I don't have good knowledge about jsdom and leaflet, I'm trying to understand them like L_PREFER_CANVAS is not working on my fork

**Comment by jieter** [comment]
L_PREFER_CANVAS is a thing of the past, pre-1.0 Leaflet.

**Comment by keremciu** [comment]
yep, because of that I deleted it and added preferCanvas as a map option on my PR https://github.com/jieter/leaflet-headless/pull/18/files

**Comment by keremciu** [comment]
thanks a lot 🎉 I will try new version when you release it

**Comment by jieter** [comment]
Updated to new version: v0.2.3
