### ISSUE TITLE
TileSize

### ISSUE THREAD

**Issue by Hyno** [jieter/leaflet-headless#21]
When using a tileSize different than 256 the map will return another map.

I'm using this code for example:

L.tileLayer( url, {tileSize: 1024} ).addTo(map);

The url returns tiles from 1024*1024 pixels. When using the same code without specifying the tileSize and using a url that returns 256x256px tiles it works fine, but when using the 1024 tiles it returns image of just the sea. Is there anything im doing wrong, or does this just not work?

Another issue is that the leaflet map that im using on my website show the same map on for example zoom level 13 as the leaflet-headless does on zoom level 15. Is there an explanation for this?

Thanks!

**Comment by jieter** [comment]
Hi @Hyno,

This is quite hard to debug without actual code/screenshots. What would be ideal to test this is having a tile set showing the requested tile url in the image.
You could also try using a different map center for debugging, maybe that does return something which is not the sea.

> Another issue is that the leaflet map that im using on my website show the same map on for example zoom level 13 as the leaflet-headless does on zoom level 15. Is there an explanation for this?
I'm guessing you maybe have a retina screen?

I'm closing this as I don't sea an issue we can fix in leaflet-headless. If you still think it's something we can fix, please reopen with a code examples/screenshots.
