### ISSUE TITLE
mapbox.js leaflet-based - headless

### ISSUE THREAD

**Issue by nyurik** [jieter/leaflet-headless#3]
Hi, I'm working on maps for Wikipedia, and it seems that the Leaflet library, plus some extras provided by [mapbox.js](https://github.com/mapbox/mapbox.js) is what I will use.  The client-side code is partially ready, but I will need server-side support to generate static snapshots, or else it will not be fast enough.  I can already stitch tiles together in the [Kartotherian service](https://github.com/kartotherian/kartotherian), but I need to overlay them with the styled GeoJSON data, which is what mapbox.js library does in the browser.  How hard do you think it would be to adapt your project to the mapbox.js?  I have also [added an issue there](https://github.com/mapbox/mapbox.js/issues/1094), in case they have some plans for it as well.  Thanks!
P.S. Your old/new New York project is very similar to the [historical proposals](https://www.mediawiki.org/wiki/Maps/Future_Plans#Historical).

**Comment by jieter** [comment]
If styling is all you need, this is a simple version of the [mapbox simplestyle example](https://www.mapbox.com/mapbox.js/example/v1.0.0/geojson-simplestyle/) (with a different tile layer):
![test-mapbox-image](https://cloud.githubusercontent.com/assets/1470389/11711782/2ca5a894-9f29-11e5-861a-9485ca5fa478.png)

[example src](https://github.com/jieter/leaflet-headless/blob/master/examples/mapbox-geojson/index.js)

Before using this in production, I think you'll at least need some form of caching for tiles as the current state of the leaflet-headless/leaflet-image combo is quite slow.

I'll be happy to merge PR's improving leaflet-headless!

**Comment by jieter** [comment]
@nyurik anything we can help with here?

**Comment by nyurik** [comment]
@jieter, sorry I did not see it earlier.  We already have all the caching in place, so that's not a problem.  Your example looks very promising - i think this is exactly what I need to make [my code](https://github.com/wikimedia/mediawiki-extensions-Kartographer/blob/master/modules/kartographer.js#L48) be adapted to work on nodejs. I just need to check that it will download the external images properly (e.g. maki icons), like [this example](http://vem.wmflabs.org/wiki/SanFrancisco).  Once again, thanks!!!

**Comment by nyurik** [comment]
@jieter hi, i tried to implement a nodejs service with the approach you suggested, but it seems it is quickly running out of memory if ran as an express service rather than a command line tool.  Can you think of what might cause this? Thanks!

**Comment by jieter** [comment]
@nyurik no idea actually, I would have to dive into that.
