### ISSUE TITLE
Add ability to set the size of the window

### ISSUE THREAD

**Issue by daamsie** [jieter/leaflet-headless#5]
I see there is this comment in the code 

// Monkey patch map.getSize to make it work with fixed 1024x1024 elements
// jsdom appears to not have clientHeight/clientWidth on elements

I really require flexible sizing for the project I'm working on, so I'm going to try to find a workaround for this.

**Comment by jieter** [comment]
Please open a PR adding this functionality. Would be nice to have this at least accessible via some API in stead of hardcoded into leaflet-headless source..

**Comment by daamsie** [comment]
Feels a bit hacky setting that in GLOBAL but it works. See if you think it's ok to be merged.

**Comment by jieter** [comment]
fixed by #6
